# Generated by Django 4.2.11 on 2024-03-22 18:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySemesterDeleteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_result', models.CharField(choices=[('1', 'Without years'), ('0', 'With years')], default='0', max_length=64)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('superviser_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentEducationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_education_file', models.ImageField(upload_to='employment_education_file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
                ('certificate_place', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
