# Generated by Django 4.2.11 on 2024-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='corequisite',
            field=models.ManyToManyField(blank=True, related_name='corequisites', to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='postrequisites', to='lesson.lesson'),
        ),
    ]
