# Generated by Django 4.2.11 on 2024-03-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_corequisite_alter_lesson_prerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='college',
            new_name='faculty',
        ),
    ]
