# Generated by Django 4.2.11 on 2024-03-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_initial'),
        ('lesson', '0003_rename_college_lesson_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='college.faculty'),
        ),
    ]
