# Generated by Django 4.2.11 on 2024-03-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_lesson_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presented', to='lesson.lesson'),
        ),
    ]
