# Generated by Django 4.2.11 on 2024-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_termlesson_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
