# Generated by Django 4.2.11 on 2024-03-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectunit',
            name='on_demand_courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='learngroup',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_groups', to='college.college'),
        ),
        migrations.AddField(
            model_name='field',
            name='learn_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='college.learngroup'),
        ),
    ]
