# Generated by Django 4.2.11 on 2024-03-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='degrees',
            new_name='degree',
        ),
    ]
