# Generated by Django 4.2.11 on 2024-03-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='دانشکده'),
        ),
    ]
