# Generated by Django 4.2.11 on 2024-03-30 11:49

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_assistant_user_alter_professor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, validators=[account.validators.is_valid_national_code], verbose_name='کد ملی'),
        ),
    ]
