# Generated by Django 4.2.11 on 2024-03-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to='account.professor'),
            preserve_default=False,
        ),
    ]
