# Generated by Django 4.2.11 on 2024-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_student_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
